name: whl2conda-dev
channels:
  - conda-forge
dependencies:
  - python >=3.8,<3.12
  # runtime
  - conda-package-handling >=2.2,<3.0
  - platformdirs >=3.10
  - tomlkit >=0.12
  - wheel >=0.41
  # build
  - hatchling >=1.18,<2.0
  - make >=4.3
  # testing
  - mypy >=1.5,<2.0
  - pylint >=2.17,<3.0
  - pytest >=7.4,<8.0
  - pytest-cov >=4.1.0,<5.0
  # documentation
  - black >=23.7
  - mike >=1.1,<2.0
  - mkdocs >=1.5,<2.0
  - mkdocstrings-python >=1.3,<2.0
  - mkdocs-material >9.1
