name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: whl2conda-dev
        environment-file: environment.yml
        python-version: 3.10
#          condarc-file: etc/example-condarc.yml
        auto-activate-base: true
    - name: Lint with pylint, mypy and black
      run: |
        make lint
    - name: Test with pytest
      run: |
        make coverage
